services:
  web:
    build: .
    container_name: moviedb_web
    command: flask --app moviedb run --host 0.0.0.0 --port=8000
    restart: always
    stop_signal: SIGINT
    volumes:
      - .:/usr/src/app/
      - ./datasets/imdb:/data/imdb:ro
      - ./datasets/tmdb:/data/tmdb:ro
      - ./datasets/hf:/data/hf:ro
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
    depends_on:
      - db
    networks:
      - default
      - proxy-network

  db:
    image: postgres:13-alpine
    container_name: moviedb_postgres
    restart: always
    environment:
      - POSTGRES_DB=admin_db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_pass
    volumes:
      - postgres_db:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: moviedb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: passwd
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
      - proxy-network

volumes:
  postgres_db:
  pgadmin-data:

networks:
  proxy-network:
    external: true
