"""Add unaccented movie name

Revision ID: 5f5c5d68767e
Revises: d476cb8c475f
Create Date: 2024-05-09 19:38:15.759808

"""

import unicodedata
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from semwork.models.movie import Movie


# revision identifiers, used by Alembic.
revision = '5f5c5d68767e'
down_revision = 'd476cb8c475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('unaccented_name', sa.String(), nullable=True))

    session = sessionmaker(bind=op.get_bind())()
    for row in session.query(Movie).all():
        row.unaccented_name = (
            unicodedata.normalize('NFD', row.name)
            .encode('ASCII', 'ignore')
            .decode("utf-8")
        )

    session.commit()
    session.close()

    op.alter_column('movie', 'unaccented_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('unaccented_name')

    # ### end Alembic commands ###
