"""Initial migration

Revision ID: d476cb8c475f
Revises: 
Create Date: 2024-05-09 19:36:25.439414

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd476cb8c475f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column(
            'meta_score',
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column(
            'meta_score',
            existing_type=sa.Integer(),
            type_=sa.DOUBLE_PRECISION(precision=53),
            existing_nullable=True,
        )

    op.create_table(
        'rating',
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'value',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='rating_movie_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rating_user_id_fkey'),
        sa.PrimaryKeyConstraint('user_id', 'movie_id', name='rating_pkey'),
    )
    # ### end Alembic commands ###
